-- Run this once in Supabase: SQL Editor -> New query -> Run.

create table if not exists public.bets (
  id bigint generated by default as identity primary key,
  sportsbook text not null default 'Unknown',
  sportsbook_bet_id text,
  status text,
  bet_type text,
  leg_count integer,
  current_odds integer,
  original_odds integer,
  boosted_odds integer,
  stake double precision,
  to_pay double precision,
  paid double precision,
  cash_out double precision,
  promo text,
  placed_at text,
  sport text,
  headline text,
  subtitle text,
  event_name text,
  raw_ocr_text text,
  screenshot_hash text unique,
  source_filename text,
  normalized_json text not null default '{}',
  draftkings_share_url text,
  fanatics_share_url text,
  fanatics_shortlink text,
  source_email_id text,
  source_email_subject text,
  espn_season_year integer,
  espn_season_type integer,
  espn_week integer,
  screenshot_path text,
  screenshot_url text,
  created_at timestamptz not null default now()
);

create unique index if not exists bets_sportsbook_bet_id_unique
  on public.bets (sportsbook_bet_id)
  where sportsbook_bet_id is not null and sportsbook_bet_id <> '';

create table if not exists public.bet_legs (
  id bigint generated by default as identity primary key,
  bet_row_id bigint not null references public.bets(id) on delete cascade,
  leg_index integer,
  selection text,
  market text,
  line_value text,
  direction text,
  odds integer,
  status text,
  event_time text,
  raw_leg_text text,
  event_team_a text,
  event_team_b text,
  espn_event_id text,
  live_state text,
  live_value text,
  live_updated_at text,
  tracking_scope text,
  future_season_year integer,
  future_season_type integer,
  espn_athlete_id text,
  future_state text,
  future_current double precision,
  future_games_played integer,
  future_pace double precision,
  future_updated_at text,
  fanatics_event_id text,
  fanatics_market_id text,
  fanatics_selection_id text
);

create index if not exists bet_legs_bet_row_id_idx on public.bet_legs(bet_row_id);

-- The Streamlit app uses a private Supabase secret/service key stored only in
-- Streamlit Secrets. Do not put that key in GitHub or in the iPhone Shortcut.
-- Create a Storage bucket named: bet-screenshots
-- You may leave the bucket private; screenshot_path still persists the source.
